# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('c', 'critical'), ('w', 'warning'), ('i', 'info')], default='i', max_length=1, verbose_name='severity')),
            ],
        ),
    ]
