# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antipoaching', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Event',
        ),
    ]
