# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 15:39
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('antipoaching', '0006_auto_20160529_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extra',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
