# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antipoaching', '0007_event_extra'),
        ('antipoaching', '0003_auto_20160529_1406'),
    ]

    operations = [
    ]
