# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 16:03
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('antipoaching', '0009_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extra',
            field=jsonfield.fields.JSONField(default='', null=True),
        ),
    ]
