# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antipoaching', '0011_auto_20160529_1643'),
        ('antipoaching', '0011_media_event'),
    ]

    operations = [
    ]
