# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antipoaching', '0012_merge'),
        ('antipoaching', '0012_media_event'),
    ]

    operations = [
    ]
